nohup python generate_word_training_data.py /mnt/noise_bmp/ 0 2  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 2 4  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 4 6  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 6 8  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 8 10  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 10 12  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 12 14  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 14 16  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 16 18  >/dev/null 2>&1 &
nohup python generate_word_training_data.py /mnt/noise_bmp/ 18 20  >/dev/null 2>&1 &
